services:
  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USE: uno
      POSTGRES_PASSWORD: uno
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres: /var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - microservices-net
    restart: unless-stopped


networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:


